### ISSUE TITLE
won't compile from a new git clone

### ISSUE THREAD

**Issue by survivant** [fuinorg/keycloak-admin-client-wrapper#1]
I try your pull request, but your project in not in a maven repository, so I clone this repo and when I try to compile it.. it looking for the parent.  

$ mvn install
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for org.fuin:keycloak-admin-client-wrapper:0.1.0-SNAPSHOT: Could not find artifact org.fuin:pom:pom:1.7.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 7, column 13
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project org.fuin:keycloak-admin-client-wrapper:0.1.0-SNAPSHOT (F:\workspace-opensource\keycloak-admin-client-wrapper\pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.fuin:keycloak-admin-client-wrapper:0.1.0-SNAPSHOT: Could not find artifact org.fuin:pom:pom:1.7.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 7, column 13 -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException

**Comment by michael-schnell** [comment]
I haven't released the Java 11 artifacts of my open source repositories yet. All released variants are still Java 8 based.

All Java 11 snapshots (inlcuding the parent pom "org.fuin:pom:pom:1.7.0-SNAPSHOT") can be found on the OSS Sonatype Snapshots Repository. If you use the snapshot repository, there is no need to checkout and compile this project on your own.

You can add the following to your .m2/settings.xml to enable snapshots in your Maven build:

```xml
<repository>
    <id>sonatype.oss.snapshots</id>
    <name>Sonatype OSS Snapshot Repository</name>
    <url>http://oss.sonatype.org/content/repositories/snapshots</url>
    <releases>
        <enabled>false</enabled>
    </releases>
    <snapshots>
        <enabled>true</enabled>
    </snapshots>
</repository>
```
(Attached you'll find a full example of such a "settings.xml" - Caution, it's named ".txt" because Github does not allow uploading XML files, so you have to rename it).

Another option would be to add it directly to your project's pom.xml:

```xml
<repositories>
  <repository>
      <id>sonatype.oss.snapshots</id>
      <name>Sonatype OSS Snapshot Repository</name>
      <url>http://oss.sonatype.org/content/repositories/snapshots</url>
      <releases>
          <enabled>false</enabled>
      </releases>
      <snapshots>
          <enabled>true</enabled>
      </snapshots>
  </repository>
</repositories>

```


[settings.xml.txt](https://github.com/fuinorg/keycloak-admin-client-wrapper/files/4908457/settings.xml.txt)

**Comment by michael-schnell** [comment]
Just release 0.1.0 - Should work now out of the box with artifacts on Maven Central
